name: user_repository
description: A repository for user data
publich_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5  
  path_provider: ^2.0.1
  http_parser: ^4.0.1
  http: ^1.2.0
  intl: ^0.18.0
  shared_preferences: ^2.0.8




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  

flutter:
  uses-material-design: true