name: innerspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  user_repository: 
    path: packages/user_repository  
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1 
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5  
  firebase_auth: ^4.17.0
  cupertino_icons: ^1.0.6
  email_validator: ^2.0.1
  password_strength: ^0.2.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.0.8
  cloud_firestore_platform_interface: ^6.1.1
  quickalert: ^1.0.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.3.1
  image_picker: ^1.0.8
  image_cropper: ^5.0.1
  iconsax: ^0.0.8
  cupertino_date_textbox: ^1.0.3
  intl: ^0.18.0
  http: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  avatar_glow: ^3.0.1
  record: ^5.0.5
  just_audio: ^0.9.38
  flutter_client_sse: ^2.0.1
  top_snackbar_flutter: ^3.1.0
  video_player: ^2.8.7
  
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf    
            
