name: innerspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.1 
  flutter_launcher_icons: ^0.13.1 
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5  
  firebase_auth: ^4.10.0
  cupertino_icons: ^1.0.6
  email_validator: ^2.0.1
  password_strength: ^0.2.0
  google_fonts: ^6.1.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.0.8

  user_repository: 
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
